### PR TITLE
Transfer Endpoints

### PR DESCRIPTION
**Pull request by DanielSollis**
Implements the three endpoints that make up the TRP protocol.

These are the four important endpoints to test in this TRP implementation and their associated helper endpoints:

- register (with the helper endpoints listusers and gettraveladdress)
- transfer (with the helper endpoint gettransfer)
- transferinquiry
- transferconfirmation

Each of these four parts of the PR can be reviewed separately

An overview diagram of the TRP protocol can be found here: https://gitlab.com/OpenVASP/travel-rule-protocol/-/blob/master/core/specification.md#overview

And the expected protocol flow can be found here: https://gitlab.com/OpenVASP/travel-rule-protocol/-/blob/master/core/specification.md#detailed-protocol-flow

To run the TRP server you should `go install ` the CLI tool found in `https://github.com/trisacrypto/testnet/cmd/openvasp/main.go` provides commands for interacting with each endpoint in the Gin server.

### For TRP server as Beneficiary 
The initial step for the TRP protocol (at least in this implementation) would be to register a new contact with the TRP server and generate an LNURL for that contact. You can use the CLI tool's `register` command to test this endpoint, the address of the gin server and the name, asset type and wallet address of the OpenVASP customer with the command's flags, but defaults are also currently provided for this as well as every other command.

You can see a list of the registered users by calling the `listusers` endpoint or using it's corresponding CLI command. You can also use the `gettraveladdress` to list a specific user's LNURL.

The next step is to initiate a TRP transfer using the LNURL generated by registering the new contact. The LNURL should be given to the transfer command through the CLI. After the transfer command has run successfully you get view the created pending transfer with the `gettransfer` endpoint or it's corresponding command, providing the transfer id of the transfer, returned by the `transfer endpoint`.

The last endpoint for beneficiary testing is the transferconfirmation endpoint. Sending either a confirmation (a txid) or a rejection to that endpoint is the last part of the TRP protocol. There is a CLI command called `confirm` for testing this endpoint.

### For TRP server as Originator
For the end-to-end demo we'll need to use 21 Analytics server, but as far as reviewing and testing this we just need to make sure that the transferinquiry endpoint works as expected based on the TRP spec and expected protocol flow. There is a CLI command called `resolve` for testing this endpoint.

### CODE REVIEW

**Comment by rebeccabilbro** [comment]
@DanielSollis, just going to capture the results of the running each of the above commands in the CLI so that it all looks like what you expect to see

```bash
pepper:testnet rebeccabilbro$ openvasp register
{
    "ID": 1,
    "CreatedAt": "2023-07-07T09:49:26.341448-04:00",
    "UpdatedAt": "2023-07-07T09:49:26.341448-04:00",
    "DeletedAt": null,
    "CustomerID": "1c39fb16-c0d0-4347-bc37-0c468d93a59b",
    "Name": "Tildred Milcot",
    "AssetType": 3,
    "WalletAddress": "926ca69a-6c22-42e6-9105-11ab5de1237b",
    "TravelAddress": "LNURL1DP68GUP69UHKCMMRV9KXSMMNWSARGDPNX5HHGUNPDEEKVETJ9UUNYDNRVYMRJCFDXE3NYV3DXSEX2D3D8YCNQDFDXYCKZC34V3JNZV3NXA3R7ARPVU7HGUNPWEJKC5N4D3J5JMN3W45HY7GQ9NV7V"
}
```

```
pepper:testnet rebeccabilbro$ openvasp listusers
[
    {
        "CustomerID": "1c39fb16-c0d0-4347-bc37-0c468d93a59b",
        "Name": "Tildred Milcot",
        "LNURL": "LNURL1DP68GUP69UHKCMMRV9KXSMMNWSARGDPNX5HHGUNPDEEKVETJ9UUNYDNRVYMRJCFDXE3NYV3DXSEX2D3D8YCNQDFDXYCKZC34V3JNZV3NXA3R7ARPVU7HGUNPWEJKC5N4D3J5JMN3W45HY7GQ9NV7V"
    }
]
```

```
pepper:testnet rebeccabilbro$ openvasp gettraveladdress
{
    "CustomerID": "00000000-0000-0000-0000-000000000000",
    "Name": "",
    "LNURL": ""
}
```

```
pepper:testnet rebeccabilbro$ openvasp transfer
{
    "Approved": {
        "Address": "payment address",
        "Callback": "http://localhost:4435/transferConfirmation?q=7e6a442c-f417-4c29-875b-2a02c3fc8a3b"
    },
    "Rejected": ""
}
```

```
pepper:testnet rebeccabilbro$ openvasp gettransfer
{
    "Could not find transfer": {}
}{
    "ID": 0,
    "CreatedAt": "0001-01-01T00:00:00Z",
    "UpdatedAt": "0001-01-01T00:00:00Z",
    "DeletedAt": null,
    "TransferID": "00000000-0000-0000-0000-000000000000",
    "Status": 0,
    "OriginatorVasp": "",
    "Originator": "",
    "Beneficiary": "",
    "AssetType": 0,
    "Amount": 0,
    "Created": "0001-01-01T00:00:00Z"
}
```

☝️ this one triggered this error on the server side:
```
[GIN-debug] [WARNING] Headers were already written. Wanted to override status code 500 with 200
[GIN] 2023/07/07 - 09:54:54 | 500 |     118.292µs |       127.0.0.1 | GET      "/gettransfer/a6f1c411-5cc0-4867-b0eb-5f4806c70803"
```

This one didn't appear to return anything 👇 to the CLI:
```
pepper:testnet rebeccabilbro$ openvasp confirm


```
but the server seemed to say 200:
```
[GIN] 2023/07/07 - 09:56:22 | 200 |    3.954583ms |       127.0.0.1 | POST     "/transferconfirmation/a6f1c411-5cc0-4867-b0eb-5f4806c70803"
```

**Review by rebeccabilbro — COMMENTED** [review]
Hey there @DanielSollis , just took a first pass through your instructions, which were excellent. 

Thank you for including links to the external docs and diagrams; the TRP protocol is just different enough from TRISA that it took me a good 20 minutes to figure out how they model the information flows. 

I was able to successfully install the CLI, and I ran all of the commands listed in your instructions. I've noted what the outcomes of each were.

There were two commands that triggered errors - one on the server side (`openvasp gettransfer` threw a 500) and one on the client side (`openvasp resolve` panicked).  It could be that I just misused the CLI, or that there's still a few bugs, but I'm not sure. Want to look through and let me know?

**Comment by DanielSollis** [comment]
The not found for the getTransfer makes since because the CLI's default transfer ID it's looking up is one that is in my local database, I should probably remove that default and make the `id` param required, same with the `gettraveladdress` command. If you ran `openvasp gettransfer -i 7e6a442c-f417-4c29-875b-2a02c3fc8a3b` the command should work correctly.

**Comment by DanielSollis** [comment]
@rebeccabilbro I pushed a commit that should resolve your initial issues

**Pull request closed without merging**
